source("packages.R")
source("testy.R")
source("errors.R")
source("logistic trend.R")
source("script2.R")
source("datafoo.R")
source("arima2.R")
source("writedata2.R")
source("means.R")
source("merge NAs.R")
